### ISSUE TITLE
Doesn't seem to work at all anymore

### ISSUE THREAD

**Issue by lkeels** [VR51/Import-External-Images-2#12]
Just doesn't do anything anymore. The import images window just doesn't show up on imported posts at all.

**Comment by dnajcz** [comment]
I had to modify line no. 439 in import-external-images.php to:
`if ( $uriCheck != '' && preg_match( '/^http:\/\//' , $uri ) ) {`
Then it was working...

**Comment by VR51** [comment]
Thanks for catching this. I restored the protocol check. You need to change http to https?.

`if ( $uriCheck != '' && preg_match( '/^https?:\/\//' , $uri ) ) {`

**Comment by lkeels** [comment]
Um, a little better explanation please...WE need to change it? Change it where? Is the code here fixed?

**Comment by VR51** [comment]
The code in the repository here has been fixed. Version 2.0.6 is available for download.
