### ISSUE TITLE
Suggestion for upload image attribute

### ISSUE THREAD

**Issue by Iquaridys** [VR51/Import-External-Images-2#16]
hello, this plugin work fine, sometime cant change link the url buy image upoad in media.
I have suggestion, can u add import the alt attribute in image to alt image in media too ?

see this plugin: https://github.com/airani/wp-auto-upload
this plugin do jobs like your plugin, plugin work fine too but when edit post, he can duplicate image in media.
of course this for reference, sometime this plugin can upload image to media and change url in post, with your plugin can't do it.

**Comment by Iquaridys** [comment]
sory the alt work fine, thanks.

but sometimes, need save draft 3 - 10x, to upload images.

**Comment by VR51** [comment]
The plugin needs a little attention. I have plans for the plugin but I'm short on time. As soon as a weekend opens up I will add a few improvements.
