### ISSUE TITLE
Plugin errors out with a very large amount of posts on a site.

### ISSUE THREAD

**Issue by adamwhitlock1** [VR51/Import-External-Images-2#8]
I have a site with over 30,000 posts that have spanned the last 15 years. Long story short if I try and run the process all posts I get a memory error
Fatal error: Allowed memory size of 786432000 bytes exhausted (tried to allocate 32 bytes) in /home/impactlabtest/public_html/wp-includes/wp-db.php on line 1889

Since i've allocated 1gb of ram to wp itself I dont think I can allocate any more memory to help with this. Any other suggestions? Could I modify the plugin to only get the posts 1-1000 or something like that so I could just do a certain amount of images at a time?

Thanks for your help

**Comment by VR51** [comment]
The plugin's settings page that allows you to import all images at once includes an option to limit the import size to a set number of images. Try this option https://github.com/VR51/Import-External-Images-2/blob/master/screenshot-1.png

Edit to add. Just thought, did you increase the PHP script timeout length?

**Comment by adamwhitlock1** [comment]
I will try increasing the script timeout length as well thanks. I tried the" limited number" import options (even tried just like 5 posts) but got the same error, and I think the primary error happens before it even gets to importing anything since the "import images" tab errors out showing the above stated error under the "Process all posts" section.

![screenshot from 2018-06-17 13-39-20](https://user-images.githubusercontent.com/8332986/41511437-e77ae3a2-7233-11e8-98d2-94b31375837d.png)


It looks like since the import-external-images.php is trying to first get all posts first, that is where the error is really occurring.

![screenshot from 2018-06-17 13-36-42](https://user-images.githubusercontent.com/8332986/41511421-9ef264a2-7233-11e8-911d-f6ae0de6c701.png)

**Comment by VR51** [comment]
I think you are right. I will take a look.

**Comment by adamwhitlock1** [comment]
It's all good. I went a more manual route and manually imported all the media i needed, then did an SQL find and replace. I would imagine most users wouldn't have to deal with 35,000+ posts with images like I did. Thanks though for the great work updating this plugin from the one Marty had made! Appreciate it
